
import type { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Nebula Glitch Tee',
    price: 35.00,
    imageUrls: [
      'https://picsum.photos/seed/ryzout1-1/600/600',
      'https://picsum.photos/seed/ryzout1-2/600/600',
      'https://picsum.photos/seed/ryzout1-3/600/600',
    ],
    category: 'Graphic Tees',
    gender: 'Unisex',
    isNewDrop: true,
    story: "This design captures the beautiful chaos of creation. The 'glitch' isn't an error; it's a moment of transformation, a reminder that our imperfections are what make our journey cosmic and unique. Wear it as a symbol that even in the vast, unknown nebula of your life, you are a spectacular event.",
  },
  {
    id: 2,
    name: 'Urban Echo Tee',
    price: 29.99,
    imageUrls: [
      'https://picsum.photos/seed/ryzout2-1/600/600',
      'https://picsum.photos/seed/ryzout2-2/600/600',
      'https://picsum.photos/seed/ryzout2-3/600/600',
    ],
    category: 'Streetwear',
    gender: 'Men',
    isNewDrop: true,
    story: "In the heart of the concrete jungle, your voice matters. This tee is an ode to the relentless spirit of the city—the dreamers, the creators, the innovators. Let it be a reminder that your actions, your art, and your ideas echo through the streets, shaping the culture of tomorrow. Be loud. Be bold. Be the echo.",
  },
  {
    id: 3,
    name: 'Cyber Core Tee',
    price: 39.50,
    imageUrls: [
      'https://picsum.photos/seed/ryzout3-1/600/600',
      'https://picsum.photos/seed/ryzout3-2/600/600',
      'https://picsum.photos/seed/ryzout3-3/600/600',
    ],
    category: 'Techwear',
    gender: 'Women',
    isNewDrop: true,
    story: "The future is not something we enter; it is something we create. The 'Cyber Core' represents the fusion of human spirit and digital frontier. It's for those who build new worlds with lines of code and strokes of genius. This tee is your armor in the digital age, a statement that you are at the core of the revolution.",
  },
  {
    id: 4,
    name: 'Minimalist Wave Tee',
    price: 28.00,
    imageUrls: [
      'https://picsum.photos/seed/ryzout4-1/600/600',
      'https://picsum.photos/seed/ryzout4-2/600/600',
      'https://picsum.photos/seed/ryzout4-3/600/600',
    ],
    category: 'Minimalist',
    gender: 'Unisex',
    isNewDrop: true,
    story: "Simplicity is the ultimate sophistication. The 'Minimalist Wave' tee represents the calm in the chaos, a single, perfect line that defines a universe of possibilities. It’s for the clear-thinker, the one who finds power in quiet confidence. Wear it as a reminder that the most profound statements are often the most simple.",
  },
  {
    id: 5,
    name: 'Retrograde Tee',
    price: 32.00,
    imageUrls: [
      'https://picsum.photos/seed/ryzout5-1/600/600',
      'https://picsum.photos/seed/ryzout5-2/600/600',
      'https://picsum.photos/seed/ryzout5-3/600/600',
    ],
    category: 'Vintage',
    gender: 'Men',
    story: "A nod to the golden age of analog, the 'Retrograde' tee is a tribute to timeless cool. It’s about the raw, unfiltered energy of vinyl records, classic cars, and neon-drenched nights. This isn’t a throwback; it’s a rebellion against the fleeting trends of today. Wear it and own your classic, unapologetic style.",
  },
  {
    id: 6,
    name: 'Chromatic Flow Tee',
    price: 36.00,
    imageUrls: [
      'https://picsum.photos/seed/ryzout6-1/600/600',
      'https://picsum.photos/seed/ryzout6-2/600/600',
      'https://picsum.photos/seed/ryzout6-3/600/600',
    ],
    category: 'Abstract',
    gender: 'Women',
    story: "Life isn’t lived in black and white. The 'Chromatic Flow' tee is a celebration of vibrant energy and fluid motion. Each color represents a different path, a different mood, a different dream, all converging into a masterpiece of self-expression. It’s for the bold, the artistic, the one who paints their own reality. Let your colors flow.",
  },
  {
    id: 7,
    name: 'Asphalt Knight Tee',
    price: 42.00,
    imageUrls: [
      'https://picsum.photos/seed/ryzout7-1/600/600',
      'https://picsum.photos/seed/ryzout7-2/600/600',
      'https://picsum.photos/seed/ryzout7-3/600/600',
    ],
    category: 'Streetwear',
    gender: 'Men',
    story: "The city is your kingdom, the streets your domain. The 'Asphalt Knight' tee is for the modern guardian of the urban landscape. It embodies the strength, resilience, and silent confidence required to navigate the concrete maze. It’s more than a shirt; it’s armor for the metropolitan warrior. Rule your city.",
  },
  {
    id: 8,
    name: 'Void Origin Tee',
    price: 30.00,
    imageUrls: [
      'https://picsum.photos/seed/ryzout8-1/600/600',
      'https://picsum.photos/seed/ryzout8-2/600/600',
      'https://picsum.photos/seed/ryzout8-3/600/600',
    ],
    category: 'Minimalist',
    gender: 'Women',
  },
  {
    id: 9,
    name: 'Digital Prophet Tee',
    price: 38.00,
    imageUrls: [
      'https://picsum.photos/seed/ryzout9-1/600/600',
      'https://picsum.photos/seed/ryzout9-2/600/600',
      'https://picsum.photos/seed/ryzout9-3/600/600',
    ],
    category: 'Techwear',
    gender: 'Men',
  },
  {
    id: 10,
    name: 'Pastel Dream Tee',
    price: 34.00,
    imageUrls: [
      'https://picsum.photos/seed/ryzout10-1/600/600',
      'https://picsum.photos/seed/ryzout10-2/600/600',
      'https://picsum.photos/seed/ryzout10-3/600/600',
    ],
    category: 'Abstract',
    gender: 'Women',
  },
  {
    id: 11,
    name: 'Concrete Jungle Tee',
    price: 33.00,
    imageUrls: [
      'https://picsum.photos/seed/ryzout11-1/600/600',
      'https://picsum.photos/seed/ryzout11-2/600/600',
      'https://picsum.photos/seed/ryzout11-3/600/600',
    ],
    category: 'Streetwear',
    gender: 'Unisex',
  },
  {
    id: 12,
    name: 'Glimmer Dust Tee',
    price: 45.00,
    imageUrls: [
      'https://picsum.photos/seed/ryzout12-1/600/600',
      'https://picsum.photos/seed/ryzout12-2/600/600',
      'https://picsum.photos/seed/ryzout12-3/600/600',
    ],
    category: 'Graphic Tees',
    gender: 'Women',
  },
];